### ISSUE TITLE
White on white things...

### ISSUE THREAD

**Issue by ofekashery** [liri/lovelace-themes#1]
I'm not sure there's a way to make everything white, here are some examples:

![image](https://user-images.githubusercontent.com/16443111/58099186-d30abe00-7be3-11e9-8559-db9ac0cec61f.png)
![image](https://user-images.githubusercontent.com/16443111/58099348-1b29e080-7be4-11e9-9a66-33c709755d8a.png)
-----
![image](https://user-images.githubusercontent.com/16443111/58099420-414f8080-7be4-11e9-9644-93f663d09fce.png)
![image](https://user-images.githubusercontent.com/16443111/58099431-4a405200-7be4-11e9-8ba5-07e0c0dce0ba.png)

**Comment by liri** [comment]
you're right, they have a "bug" on some panels, i've opened a pull requests for that. 
anyway most of the UI currently looks valid to me at this point.

will update if they merge my request.

**Comment by ofekashery** [comment]
Thanks!
Your pull request will not fix my first image - the switch "on" icon also uses the ``primary-color``.

**Comment by liri** [comment]
you sure it's not mdc-button? if so - there's a different variable for these
