### ISSUE TITLE
Google - Light theme header background is black

### ISSUE THREAD

**Issue by nickw444** [liri/lovelace-themes#11]
It seems the background color is black, which makes the overlayed text and button not visible: 

![Screen Shot 2020-04-03 at 23 16 07](https://user-images.githubusercontent.com/1289759/78359624-2a016200-7601-11ea-8865-2e353984bd27.png)

I would imagine it should have a white background color, something like this:

![Screen Shot 2020-04-03 at 23 17 23](https://user-images.githubusercontent.com/1289759/78359688-48675d80-7601-11ea-818e-507a6eb11964.png)

**Comment by liri** [comment]
https://github.com/home-assistant/frontend/issues/5529

**Comment by yusijs** [comment]
@liri not sure this is 100% accurate (or well, it could be - I have no clue) because I was able to "fix" this on my installation:

```
    ### Main Interface Colors ###
    app-header-background-color: "#000000"
    primary-color: "#ffffff" # This was the first issue - this was applied as the background
    light-primary-color: "#2b2b2b"
    primary-background-color: "#000000"
    secondary-background-color: "#2b2b2b"
    divider-color: "#2b2b2b"
    ### Text ###
    primary-text-color: var(--primary-color) # This was the secondary issue - this was applied as the font color, but it used the primary-color variable.
    secondary-text-color: "#d7d7d7"
    text-primary-color: "#ffffff"
    disabled-text-color: "#a1a1a1"
```

By changing the primary-color to #2b2b2b and the primary-text-color to #ffffff, it looks great to me.
