### ISSUE TITLE
Some colors are wrong

### ISSUE THREAD

**Issue by escoand** [liri/lovelace-themes#3]
Thanks for this nice theme, really like it. But I have at least 2 problems where there are wrong colors.

First `media-control` card when nothing is played.
![Screenshot_20190918-162107](https://user-images.githubusercontent.com/428567/65157432-06921380-da31-11e9-81c8-89d6bb5fd6aa.png)

And secondly the states developer tools page:
![Screenshot_20190918-162949](https://user-images.githubusercontent.com/428567/65157993-e4e55c00-da31-11e9-9b51-8215e3651b1b.png)

**Comment by javiermejiacorona** [comment]
I figure out the same, the switches when they are on are "white" :(

**Comment by liri** [comment]
Hi, I've tried to find a workaround to the above issue with the media player and links but unfortunately there's no way to differentiate them from the primary color which also controls the header background color. We'll have to wait for the devs to provide a different variables for it.. sorry.

**Comment by liri** [comment]
> I figure out the same, the switches when they are on are "white" :(

@javiermejiacorona switches are fixed in version 1.0.1 enjoy

**Comment by liri** [comment]
Hello again, a solution for setting the app toolbar was committed recently (https://github.com/home-assistant/home-assistant-polymer/pull/4269), i'll verify it's fixing the current primary color issues and update soon.

**Comment by liri** [comment]
fixed in v1.0.2
