### ISSUE TITLE
[OT] How do you list group.all_devices on the UI?

### ISSUE THREAD

**Issue by yegle** [liri/lovelace-themes#4]
In this screenshot https://raw.githubusercontent.com/liri/lovelace-themes/master/screenshots/Google%20-%20Light/5.JPG I see you have devices listed on the UI. I'm assuming it's `group.all_devices`, but how do you make it show all the devices?

I tried to add `group.all_devices` entity to my UI but you have to click that to view the devices.

**Comment by liri** [comment]
Hi @yegle, it's a simple entities card with all devices listed
