### ISSUE TITLE
Confirmation Button Background and Text are the same color

### ISSUE THREAD

**Issue by jscott304** [liri/lovelace-themes#8]
When I click uninstall on HACS in either the light or dark themes the button and text are the same color

**Comment by liri** [comment]
Hi @jscott304, thanks for your feedback. since I don't use HACS I can't work on a fix atm. I can try and suggest to use HACS theme variables and it might solve your issue for the time being.
I hope someone can make a pull request with such fix soon.

**Comment by GreyEarl** [comment]
Seems the default primary-background-color is taken into account. Also it seems the HACS theme variables are very limited.

![image](https://user-images.githubusercontent.com/33351068/74067327-4d40d400-49f9-11ea-9caa-c77bca9b9b23.png)

**Comment by liri** [comment]
can you please test it with v1.0.3?
